- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: install software
    ansible.builtin.package:
      name: "{{item}}"
      state: present
    loop:
    - git
    - mysql
    - postfix
